version: '2'

services:
    r1:
        image: redis-ha
        network_mode: "host"
        environment:
            - "NET_IFACE=wlan0"
            - "PORT0=28118"

    r2:
        image: redis-ha
        network_mode: "host"
        environment:
            - "NET_IFACE=wlan0"
            - "PORT0=31131"

    r3:
        image: redis-ha
        network_mode: "host"
        environment:
            - "NET_IFACE=wlan0"
            - "PORT0=16880"

    s1:
        image: redis-ha-sentinel
        network_mode: "host"
        environment:
            - "NET_IFACE=wlan0"
            - "PORT0=19107"

    s2:
        image: redis-ha-sentinel
        network_mode: "host"
        environment:
            - "NET_IFACE=wlan0"
            - "PORT0=5629"

    s3:
        image: redis-ha-sentinel
        network_mode: "host"
        environment:
            - "NET_IFACE=wlan0"
            - "PORT0=12226"

    zk:
        image: mesoscloud/zookeeper:3.4.8-ubuntu
        network_mode: "host"
        environment:
            - node1
            - MYID=1
